APT::FTPArchive::Release::Origin "kubara-io";
APT::FTPArchive::Release::Label "Kubara";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64 arm64";
APT::FTPArchive::Release::Components "main";
